--<ScriptOptions statementTerminator="GO"/>

ALTER TABLE "dbo"."Vacxin" DROP CONSTRAINT "PK__Vacxin__38F645DC2E1BDC42"
GO

DROP TABLE "dbo"."Vacxin"
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE "dbo"."Vacxin" (
	"idVaccine" null NOT NULL,
	"tenVaccine" null,
	"soluong" INT,
	CONSTRAINT "PK__Vacxin__38F645DC2E1BDC42" PRIMARY KEY ("idVaccine") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

SET ANSI_PADDING OFF
GO

